const FRUIT_GALLERY = [
  "/product-fallbacks/pexels-karola-g-4230621.jpg",
  "/product-fallbacks/pexels-mudrik-h-amin-1252431-2485430.jpg",
  "/product-fallbacks/pexels-pixabay-266346.jpg",
  "/product-fallbacks/pexels-pixabay-115019.jpg",
  "/product-fallbacks/charlesdeluvio-0v_1TPz1uXw-unsplash.jpg",
] as const;

const FOOD_GALLERY = [
  "/product-fallbacks/zaib-tse-KVv5lFOMY1E-unsplash.jpg",
  "/product-fallbacks/charlesdeluvio-0v_1TPz1uXw-unsplash.jpg",
  "/product-fallbacks/pexels-pixabay-115019.jpg",
  "/product-fallbacks/pexels-pixabay-266346.jpg",
  "/product-fallbacks/pexels-karola-g-4230621.jpg",
] as const;

function rotateGallery(images: readonly string[], startIndex: number): string[] {
  return Array.from({ length: 4 }, (_, offset) => images[(startIndex + offset) % images.length]);
}

function createSeedProduct(args: {
  name: string;
  price: string;
  rating: string;
  featured: boolean;
  stock: number;
  category: "fruits" | "foods";
  description: string;
  galleryIndex: number;
}) {
  const gallerySource = args.category === "fruits" ? FRUIT_GALLERY : FOOD_GALLERY;
  const imageGallery = rotateGallery(gallerySource, args.galleryIndex);

  return {
    name: args.name,
    price: args.price,
    rating: args.rating,
    featured: args.featured,
    stock: args.stock,
    category: args.category,
    imageUrl: imageGallery[0],
    imageGallery,
    description: args.description,
  };
}

export const catalogCategorySeed = [
  {
    name: "Fruits",
    slug: "fruits",
    imageUrl: FRUIT_GALLERY[4],
  },
  {
    name: "Foods",
    slug: "foods",
    imageUrl: FOOD_GALLERY[0],
  },
];

export const catalogProductSeed = [
  ...[
    {
      name: "Fresh Mango Box",
      price: "14.00",
      rating: "4.8",
      featured: true,
      stock: 35,
      category: "fruits" as const,
      galleryIndex: 0,
      description: "Sweet ripe mangoes packed fresh for smoothies, desserts, and daily snacking.",
    },
    {
      name: "Strawberry Fresh Pack",
      price: "7.60",
      rating: "4.8",
      featured: true,
      stock: 38,
      category: "fruits" as const,
      galleryIndex: 1,
      description: "Hand-picked strawberries with bright flavor, perfect for desserts and breakfast.",
    },
    {
      name: "Orange Citrus Bag",
      price: "8.20",
      rating: "4.6",
      featured: false,
      stock: 45,
      category: "fruits" as const,
      galleryIndex: 2,
      description: "Fresh citrus oranges rich in vitamin C, ideal for juice and healthy snacks.",
    },
    {
      name: "Premium Apple Mix",
      price: "9.50",
      rating: "4.7",
      featured: true,
      stock: 50,
      category: "fruits" as const,
      galleryIndex: 3,
      description: "Crisp red and green apples selected for balanced sweetness and crunch.",
    },
    {
      name: "Mixed Fruit Family Crate",
      price: "24.00",
      rating: "4.9",
      featured: true,
      stock: 12,
      category: "fruits" as const,
      galleryIndex: 4,
      description: "Family-size crate with mixed premium fruits for the whole week.",
    },
    {
      name: "Banana Value Bunch",
      price: "5.90",
      rating: "4.5",
      featured: false,
      stock: 64,
      category: "fruits" as const,
      galleryIndex: 0,
      description: "Budget-friendly bananas selected for lunch boxes, smoothies, and quick energy.",
    },
    {
      name: "Pineapple Sweet Crown",
      price: "6.80",
      rating: "4.7",
      featured: false,
      stock: 30,
      category: "fruits" as const,
      galleryIndex: 1,
      description: "Juicy pineapple with bright tropical sweetness for slicing, grilling, and juice.",
    },
    {
      name: "Seedless Grape Bowl",
      price: "8.90",
      rating: "4.6",
      featured: false,
      stock: 42,
      category: "fruits" as const,
      galleryIndex: 2,
      description: "Fresh seedless grapes with a crisp bite, ready for snacking or fruit platters.",
    },
    {
      name: "Avocado Creamy Pair",
      price: "6.40",
      rating: "4.8",
      featured: true,
      stock: 22,
      category: "fruits" as const,
      galleryIndex: 3,
      description: "Creamy avocados ideal for toast, salads, dips, and healthy breakfast bowls.",
    },
    {
      name: "Pear Orchard Pack",
      price: "7.20",
      rating: "4.5",
      featured: false,
      stock: 33,
      category: "fruits" as const,
      galleryIndex: 4,
      description: "Tender orchard pears with mellow sweetness and a smooth texture.",
    },
    {
      name: "Kiwi Fresh Tray",
      price: "8.10",
      rating: "4.6",
      featured: false,
      stock: 27,
      category: "fruits" as const,
      galleryIndex: 0,
      description: "Tangy kiwi fruits rich in flavor and color for fruit salads and desserts.",
    },
    {
      name: "Blueberry Snack Cup",
      price: "6.70",
      rating: "4.7",
      featured: true,
      stock: 29,
      category: "fruits" as const,
      galleryIndex: 1,
      description: "Fresh blueberries packed for oatmeal toppings, pancakes, and healthy snacking.",
    },
    {
      name: "Organic Vegetable Basket",
      price: "18.00",
      rating: "4.8",
      featured: true,
      stock: 28,
      category: "foods" as const,
      galleryIndex: 0,
      description: "Seasonal vegetables including carrots, peppers, tomatoes, and leafy greens.",
    },
    {
      name: "Brown Rice 1kg",
      price: "4.30",
      rating: "4.6",
      featured: false,
      stock: 70,
      category: "foods" as const,
      galleryIndex: 1,
      description: "Whole-grain brown rice with a nutty flavor for balanced everyday meals.",
    },
    {
      name: "Whole Grain Bread Loaf",
      price: "3.80",
      rating: "4.4",
      featured: false,
      stock: 40,
      category: "foods" as const,
      galleryIndex: 2,
      description: "Soft whole grain bread baked daily, perfect for sandwiches and toast.",
    },
    {
      name: "Farm Eggs (12 pcs)",
      price: "4.90",
      rating: "4.7",
      featured: false,
      stock: 46,
      category: "foods" as const,
      galleryIndex: 3,
      description: "Fresh farm eggs with rich yolks for breakfast, baking, and healthy meals.",
    },
    {
      name: "Honey Pure Jar",
      price: "7.40",
      rating: "4.8",
      featured: false,
      stock: 36,
      category: "foods" as const,
      galleryIndex: 4,
      description: "Natural pure honey, smooth and aromatic for tea, toast, and desserts.",
    },
    {
      name: "Greek Yogurt Cup",
      price: "2.90",
      rating: "4.5",
      featured: false,
      stock: 58,
      category: "foods" as const,
      galleryIndex: 0,
      description: "Creamy Greek yogurt with a rich texture for breakfast bowls and light snacks.",
    },
    {
      name: "Cheddar Cheese Block",
      price: "5.80",
      rating: "4.6",
      featured: false,
      stock: 31,
      category: "foods" as const,
      galleryIndex: 1,
      description: "Aged cheddar block with sharp flavor for sandwiches, pasta, and baked dishes.",
    },
    {
      name: "Olive Oil Bottle",
      price: "11.50",
      rating: "4.8",
      featured: true,
      stock: 24,
      category: "foods" as const,
      galleryIndex: 2,
      description: "Cold-pressed olive oil for cooking, roasting, and fresh salad dressings.",
    },
    {
      name: "Pasta Family Pack",
      price: "6.10",
      rating: "4.4",
      featured: false,
      stock: 49,
      category: "foods" as const,
      galleryIndex: 3,
      description: "Durum wheat pasta pack suited for family dinners and meal prep.",
    },
    {
      name: "Tomato Sauce Duo",
      price: "4.60",
      rating: "4.5",
      featured: false,
      stock: 43,
      category: "foods" as const,
      galleryIndex: 4,
      description: "Two-jar tomato sauce set with a slow-cooked flavor for pasta and pizza.",
    },
    {
      name: "Oatmeal Breakfast Bag",
      price: "5.20",
      rating: "4.6",
      featured: true,
      stock: 34,
      category: "foods" as const,
      galleryIndex: 0,
      description: "Whole oats for porridge, overnight oats, and fiber-rich breakfast recipes.",
    },
    {
      name: "Fresh Milk 1L",
      price: "2.70",
      rating: "4.5",
      featured: false,
      stock: 52,
      category: "foods" as const,
      galleryIndex: 1,
      description: "Fresh daily milk for cereal, coffee, baking, and family breakfasts.",
    },
    {
      name: "Chicken Breast Tray",
      price: "12.90",
      rating: "4.7",
      featured: true,
      stock: 20,
      category: "foods" as const,
      galleryIndex: 2,
      description: "Lean chicken breast portions ready for grilling, roasting, and healthy meal prep.",
    },
  ].map(createSeedProduct),
];
