const FRUIT_GALLERY = [
  "https://images.unsplash.com/photo-1619566636858-adf3ef46400b?q=80&w=1200&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1574226516831-e1dff420e37f?q=80&w=1200&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?q=80&w=1200&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?q=80&w=1200&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1519996529931-28324d5a630e?q=80&w=1200&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1615485925873-9d3f2ea10d04?q=80&w=1200&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1587132137056-bfbf0166836e?q=80&w=1200&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1488459716781-31db52582fe9?q=80&w=1200&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1584306670957-acf935f5033c?q=80&w=1200&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1515037893149-de7f840978e2?q=80&w=1200&auto=format&fit=crop",
] as const;

const FOOD_GALLERY = [
  "https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=1200&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=1200&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1498837167922-ddd27525d352?q=80&w=1200&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?q=80&w=1200&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=1200&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?q=80&w=1200&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1603048297172-c92544798d5a?q=80&w=1200&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1514996937319-344454492b37?q=80&w=1200&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1526318896980-cf78c088247c?q=80&w=1200&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1466637574441-749b8f19452f?q=80&w=1200&auto=format&fit=crop",
] as const;

function gallery(primary: string, images: readonly string[]): string[] {
  return [primary, ...images.filter((image) => image !== primary)].slice(0, 4);
}

function slugifyForImageSearch(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ",")
    .replace(/^,+|,+$/g, "")
    .slice(0, 60);
}

function createSearchImageUrl(name: string, category: "fruits" | "foods", seed: number): string {
  const keywords = slugifyForImageSearch(`${name},${category === "fruits" ? "fresh fruit" : "fresh food"}`);
  return `https://source.unsplash.com/1200x900/?${keywords}&sig=${seed}`;
}

function ensureDistinctProductMedia<T extends {
  name: string;
  category: "fruits" | "foods";
  imageUrl: string;
  imageGallery: string[];
}>(products: T[]): T[] {
  const seenPrimaryUrls = new Set<string>();

  return products.map((product, index) => {
    let primaryImage = product.imageUrl;
    if (seenPrimaryUrls.has(primaryImage)) {
      primaryImage = createSearchImageUrl(product.name, product.category, index + 1);
    }
    seenPrimaryUrls.add(primaryImage);

    const extraGallery = [
      createSearchImageUrl(`${product.name} close up`, product.category, index + 101),
      createSearchImageUrl(`${product.name} on table`, product.category, index + 201),
    ];

    const imageGallery = [primaryImage, ...product.imageGallery, ...extraGallery]
      .filter((url, galleryIndex, arr) => arr.indexOf(url) === galleryIndex)
      .slice(0, 4);

    return {
      ...product,
      imageUrl: primaryImage,
      imageGallery,
    };
  });
}

function createSeedProduct(args: {
  name: string;
  price: string;
  rating: string;
  featured: boolean;
  stock: number;
  category: "fruits" | "foods";
  description: string;
  imageUrl: string;
}) {
  const source = args.category === "fruits" ? FRUIT_GALLERY : FOOD_GALLERY;

  return {
    name: args.name,
    price: args.price,
    rating: args.rating,
    featured: args.featured,
    stock: args.stock,
    category: args.category,
    imageUrl: args.imageUrl,
    imageGallery: gallery(args.imageUrl, source),
    description: args.description,
  };
}

export const catalogCategorySeed = [
  {
    name: "Fruits",
    slug: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1619566636858-adf3ef46400b?q=80&w=1200&auto=format&fit=crop",
  },
  {
    name: "Foods",
    slug: "foods",
    imageUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=1200&auto=format&fit=crop",
  },
];

export const catalogProductSeed = ensureDistinctProductMedia([
  createSeedProduct({
    name: "Ataulfo Mango Box",
    price: "15.90",
    rating: "4.9",
    featured: true,
    stock: 28,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1553279768-865429fa0078?q=80&w=1200&auto=format&fit=crop",
    description: "6 premium yellow mangoes, naturally sweet and low fiber, packed for smoothies, fruit bowls, and dessert prep.",
  }),
  createSeedProduct({
    name: "Honeycrisp Apple Basket",
    price: "11.40",
    rating: "4.8",
    featured: true,
    stock: 42,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?q=80&w=1200&auto=format&fit=crop",
    description: "8 crisp Honeycrisp apples with balanced sweetness and crunch, ideal for lunch boxes, baking, and fresh snacking.",
  }),
  createSeedProduct({
    name: "Seedless Green Grape Punnet",
    price: "7.80",
    rating: "4.7",
    featured: false,
    stock: 36,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1537640538966-79f369143f8f?q=80&w=1200&auto=format&fit=crop",
    description: "500 g of chilled seedless green grapes, washed and packed for easy snacking, cheese boards, and school lunches.",
  }),
  createSeedProduct({
    name: "Valencia Orange Family Bag",
    price: "9.60",
    rating: "4.6",
    featured: false,
    stock: 48,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1547514701-42782101795e?q=80&w=1200&auto=format&fit=crop",
    description: "3 kg bag of juicy Valencia oranges with bright citrus flavor for fresh juice, breakfast platters, and everyday vitamin C.",
  }),
  createSeedProduct({
    name: "Blueberry Breakfast Cup",
    price: "5.90",
    rating: "4.8",
    featured: true,
    stock: 33,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1498557850523-fd3d118b962e?q=80&w=1200&auto=format&fit=crop",
    description: "Fresh 170 g blueberries with a sweet-tart finish, perfect for oatmeal, pancakes, yogurt, and quick snacking.",
  }),
  createSeedProduct({
    name: "Strawberry Dessert Pack",
    price: "6.70",
    rating: "4.8",
    featured: true,
    stock: 31,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?q=80&w=1200&auto=format&fit=crop",
    description: "400 g strawberries selected for size and color, ready for desserts, breakfast bowls, and fresh table service.",
  }),
  createSeedProduct({
    name: "Creamy Hass Avocado Duo",
    price: "4.80",
    rating: "4.7",
    featured: true,
    stock: 39,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1519162808019-7de1683fa2ad?q=80&w=1200&auto=format&fit=crop",
    description: "2 ripe Hass avocados with buttery texture, ideal for toast, salads, wraps, and guacamole.",
  }),
  createSeedProduct({
    name: "Golden Pineapple Single",
    price: "5.30",
    rating: "4.6",
    featured: false,
    stock: 24,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?q=80&w=1200&auto=format&fit=crop",
    description: "One medium golden pineapple with sweet tropical flavor for slicing, juicing, grilling, and fruit platters.",
  }),
  createSeedProduct({
    name: "Red Watermelon Half",
    price: "8.90",
    rating: "4.5",
    featured: false,
    stock: 19,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1563114773-84221bd62daa?q=80&w=1200&auto=format&fit=crop",
    description: "Fresh-cut watermelon half, chilled and ready for entertaining, hydration, and family-size fruit bowls.",
  }),
  createSeedProduct({
    name: "Kiwi Green Tray",
    price: "6.20",
    rating: "4.6",
    featured: false,
    stock: 29,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1610917040803-1fccf9623064?q=80&w=1200&auto=format&fit=crop",
    description: "6 green kiwis with bright acidity and vivid color, excellent for smoothies, fruit salads, and garnishing.",
  }),
  createSeedProduct({
    name: "Bartlett Pear Bag",
    price: "7.10",
    rating: "4.5",
    featured: false,
    stock: 27,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1574226516831-e1dff420e37f?q=80&w=1200&auto=format&fit=crop",
    description: "6 soft Bartlett pears with mellow sweetness, suited for snacking, salads, and poaching.",
  }),
  createSeedProduct({
    name: "Ruby Grapefruit Pair",
    price: "4.60",
    rating: "4.4",
    featured: false,
    stock: 22,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1577234286642-fc512a5f8f11?q=80&w=1200&auto=format&fit=crop",
    description: "2 ruby grapefruit with juicy pink flesh and a refreshing bitter-sweet flavor for breakfast and juice.",
  }),
  createSeedProduct({
    name: "Papaya Breakfast Fruit",
    price: "6.90",
    rating: "4.6",
    featured: false,
    stock: 17,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1517282009859-f000ec3b26fe?q=80&w=1200&auto=format&fit=crop",
    description: "One ripe papaya with soft orange flesh, ideal for breakfast bowls, tropical salads, and smoothies.",
  }),
  createSeedProduct({
    name: "Pomegranate Jewel Pack",
    price: "8.40",
    rating: "4.7",
    featured: true,
    stock: 21,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1541344999736-83eca272f6fc?q=80&w=1200&auto=format&fit=crop",
    description: "2 heavy pomegranates packed with ruby seeds, great for salads, yogurt, and festive fruit boards.",
  }),
  createSeedProduct({
    name: "Ripe Banana Bunch",
    price: "3.90",
    rating: "4.7",
    featured: false,
    stock: 72,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?q=80&w=1200&auto=format&fit=crop",
    description: "Approx. 1.2 kg banana bunch with dependable sweetness for smoothies, baking, and quick everyday energy.",
  }),
  createSeedProduct({
    name: "Dragon Fruit Duo",
    price: "9.80",
    rating: "4.5",
    featured: false,
    stock: 14,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1526318896980-cf78c088247c?q=80&w=1200&auto=format&fit=crop",
    description: "2 dragon fruits with dramatic color and mild sweetness, perfect for smoothie bars and plated desserts.",
  }),
  createSeedProduct({
    name: "Lemon Citrus Bag",
    price: "4.20",
    rating: "4.6",
    featured: false,
    stock: 55,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1590502593747-42a996133562?q=80&w=1200&auto=format&fit=crop",
    description: "8 lemons for cooking, dressings, baking, tea, and fresh household prep throughout the week.",
  }),
  createSeedProduct({
    name: "Lime Cocktail Pack",
    price: "4.10",
    rating: "4.5",
    featured: false,
    stock: 37,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?q=80&w=1200&auto=format&fit=crop",
    description: "10 fresh limes packed for marinades, tacos, juices, soda, and home bar mixing.",
  }),
  createSeedProduct({
    name: "Peach Summer Tray",
    price: "7.30",
    rating: "4.6",
    featured: true,
    stock: 23,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1629828874514-9cd19686e6dd?q=80&w=1200&auto=format&fit=crop",
    description: "6 fragrant peaches with soft flesh and gentle sweetness for desserts, yogurt bowls, and fresh snacking.",
  }),
  createSeedProduct({
    name: "Plum Snack Bowl",
    price: "5.60",
    rating: "4.4",
    featured: false,
    stock: 26,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?q=80&w=1200&auto=format&fit=crop",
    description: "500 g mixed plums with a sweet-tart bite, well suited for snacking, tarts, and lunchbox fruit cups.",
  }),
  createSeedProduct({
    name: "Raspberry Premium Punnet",
    price: "6.80",
    rating: "4.8",
    featured: true,
    stock: 18,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1577003833619-76bbd7f82948?q=80&w=1200&auto=format&fit=crop",
    description: "Fresh raspberries packed for bakery topping, breakfast service, cocktails, and premium dessert finishing.",
  }),
  createSeedProduct({
    name: "Cantaloupe Melon Whole",
    price: "6.50",
    rating: "4.5",
    featured: false,
    stock: 16,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1598025362874-49480e049c76?q=80&w=1200&auto=format&fit=crop",
    description: "One full cantaloupe with fragrant orange flesh, chilled and sweet for breakfast platters and smoothies.",
  }),
  createSeedProduct({
    name: "Cherry Sweet Box",
    price: "9.20",
    rating: "4.7",
    featured: true,
    stock: 20,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1528821128474-27f963b062bf?q=80&w=1200&auto=format&fit=crop",
    description: "400 g cherries with deep color and crisp bite, excellent for desserts, gifting, and weekend entertaining.",
  }),
  createSeedProduct({
    name: "Mixed Fruit Party Crate",
    price: "26.00",
    rating: "4.9",
    featured: true,
    stock: 11,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?q=80&w=1200&auto=format&fit=crop",
    description: "Large assorted fruit crate with apples, oranges, bananas, grapes, and seasonal premium fruit for households and events.",
  }),
  createSeedProduct({
    name: "Rainbow Bell Pepper Trio",
    price: "4.90",
    rating: "4.7",
    featured: true,
    stock: 34,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?q=80&w=1200&auto=format&fit=crop",
    description: "Red, yellow, and green bell peppers selected for stir-fries, roasting, salads, and lunch prep.",
  }),
  createSeedProduct({
    name: "Baby Spinach Salad Bag",
    price: "3.80",
    rating: "4.6",
    featured: false,
    stock: 30,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?q=80&w=1200&auto=format&fit=crop",
    description: "250 g washed baby spinach leaves for salads, omelets, smoothies, and quick sauteed sides.",
  }),
  createSeedProduct({
    name: "Roma Tomato Kitchen Pack",
    price: "5.20",
    rating: "4.7",
    featured: false,
    stock: 44,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?q=80&w=1200&auto=format&fit=crop",
    description: "1.5 kg Roma tomatoes with firm texture for sauces, salads, sandwiches, and home cooking.",
  }),
  createSeedProduct({
    name: "Organic Carrot Bunch",
    price: "3.40",
    rating: "4.5",
    featured: false,
    stock: 41,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1447175008436-170170753d52?q=80&w=1200&auto=format&fit=crop",
    description: "1 kg carrots with tops removed, sweet and crunchy for roasting, juicing, soups, and lunch prep.",
  }),
  createSeedProduct({
    name: "Broccoli Crown Pack",
    price: "4.30",
    rating: "4.6",
    featured: false,
    stock: 25,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?q=80&w=1200&auto=format&fit=crop",
    description: "Two fresh broccoli crowns trimmed for steaming, stir-fries, meal prep, and healthy side dishes.",
  }),
  createSeedProduct({
    name: "Yukon Gold Potato Bag",
    price: "6.60",
    rating: "4.7",
    featured: true,
    stock: 53,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=1200&auto=format&fit=crop",
    description: "2.5 kg Yukon Gold potatoes with creamy texture for roasting, mashing, wedges, and hearty dinners.",
  }),
  createSeedProduct({
    name: "Sweet Corn Four Pack",
    price: "4.70",
    rating: "4.5",
    featured: false,
    stock: 28,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?q=80&w=1200&auto=format&fit=crop",
    description: "4 ears of sweet corn, husked and cleaned for boiling, grilling, chowders, and salads.",
  }),
  createSeedProduct({
    name: "Free Range Egg Dozen",
    price: "5.10",
    rating: "4.8",
    featured: true,
    stock: 47,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1506976785307-8732e854ad03?q=80&w=1200&auto=format&fit=crop",
    description: "12 free-range eggs with rich yolks for breakfast, baking, weekly meal prep, and family cooking.",
  }),
  createSeedProduct({
    name: "Greek Yogurt Family Tub",
    price: "6.40",
    rating: "4.7",
    featured: false,
    stock: 26,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1571212515416-fca88b972a7f?q=80&w=1200&auto=format&fit=crop",
    description: "1 kg plain Greek yogurt with thick texture, ideal for breakfast bowls, sauces, dips, and marinades.",
  }),
  createSeedProduct({
    name: "Whole Milk 1 Liter",
    price: "2.80",
    rating: "4.5",
    featured: false,
    stock: 61,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1550583724-b2692b85b150?q=80&w=1200&auto=format&fit=crop",
    description: "Fresh whole milk for cereal, coffee, smoothies, baking, and everyday family use.",
  }),
  createSeedProduct({
    name: "Aged Cheddar Block",
    price: "5.90",
    rating: "4.7",
    featured: false,
    stock: 23,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1552767059-ce182ead6c1b?q=80&w=1200&auto=format&fit=crop",
    description: "250 g cheddar cheese block with a sharp finish for sandwiches, burgers, sauces, and baking.",
  }),
  createSeedProduct({
    name: "Salted Butter Twin Pack",
    price: "4.50",
    rating: "4.6",
    featured: false,
    stock: 38,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1589985270958-b8d2f4c938e4?q=80&w=1200&auto=format&fit=crop",
    description: "Two 250 g butter blocks for baking, toast, sauteing, and rich everyday cooking.",
  }),
  createSeedProduct({
    name: "Chicken Breast Meal Prep Tray",
    price: "13.90",
    rating: "4.8",
    featured: true,
    stock: 19,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?q=80&w=1200&auto=format&fit=crop",
    description: "Approx. 900 g trimmed chicken breast portions for grilling, roasting, wraps, and high-protein meal prep.",
  }),
  createSeedProduct({
    name: "Atlantic Salmon Fillet",
    price: "16.80",
    rating: "4.9",
    featured: true,
    stock: 14,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1544943910-4c1dc44aab44?q=80&w=1200&auto=format&fit=crop",
    description: "Fresh salmon fillet, skin-on, ideal for roasting, pan searing, omega-rich dinners, and premium home cooking.",
  }),
  createSeedProduct({
    name: "Lean Beef Stir Fry Strips",
    price: "12.70",
    rating: "4.6",
    featured: false,
    stock: 18,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?q=80&w=1200&auto=format&fit=crop",
    description: "500 g lean beef strips prepared for stir-fries, noodle bowls, wraps, and quick skillet meals.",
  }),
  createSeedProduct({
    name: "Jasmine Rice 2 kg",
    price: "7.20",
    rating: "4.8",
    featured: true,
    stock: 58,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?q=80&w=1200&auto=format&fit=crop",
    description: "Fragrant jasmine rice with light floral aroma, perfect for daily meals, curries, bowls, and batch cooking.",
  }),
  createSeedProduct({
    name: "Brown Rice 2 kg",
    price: "6.90",
    rating: "4.6",
    featured: false,
    stock: 46,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1516684732162-798a0062be99?q=80&w=1200&auto=format&fit=crop",
    description: "Whole grain brown rice with a nutty profile for balanced meals, lunch prep, and fiber-rich sides.",
  }),
  createSeedProduct({
    name: "Spaghetti Family Pack",
    price: "4.60",
    rating: "4.5",
    featured: false,
    stock: 63,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1551462147-ff29053bfc14?q=80&w=1200&auto=format&fit=crop",
    description: "1 kg durum wheat spaghetti for quick dinners, pantry stocking, and family-size pasta nights.",
  }),
  createSeedProduct({
    name: "Penne Rigate Pantry Pack",
    price: "4.80",
    rating: "4.5",
    featured: false,
    stock: 51,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?q=80&w=1200&auto=format&fit=crop",
    description: "1 kg ridged penne that holds sauce well, suited for baked pasta, creamy dishes, and weekly meal prep.",
  }),
  createSeedProduct({
    name: "Extra Virgin Olive Oil",
    price: "12.90",
    rating: "4.9",
    featured: true,
    stock: 29,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?q=80&w=1200&auto=format&fit=crop",
    description: "750 ml cold-pressed extra virgin olive oil for roasting, dressings, marinades, and premium kitchen use.",
  }),
  createSeedProduct({
    name: "Acacia Honey Jar",
    price: "8.10",
    rating: "4.8",
    featured: true,
    stock: 32,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1587049352851-8d4e89133924?q=80&w=1200&auto=format&fit=crop",
    description: "500 g clear acacia honey with gentle floral sweetness for tea, yogurt, toast, and baking.",
  }),
  createSeedProduct({
    name: "Rolled Oats Breakfast Bag",
    price: "5.40",
    rating: "4.7",
    featured: false,
    stock: 57,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1515543904379-3d757afe72e1?q=80&w=1200&auto=format&fit=crop",
    description: "1 kg rolled oats for porridge, overnight oats, granola, baking, and dependable breakfast prep.",
  }),
  createSeedProduct({
    name: "Crunchy Peanut Butter",
    price: "4.70",
    rating: "4.6",
    featured: false,
    stock: 35,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1622484212850-eb596d769edc?q=80&w=1200&auto=format&fit=crop",
    description: "340 g crunchy peanut butter for sandwiches, smoothies, satay sauces, and protein-rich snacks.",
  }),
  createSeedProduct({
    name: "Artisan Whole Wheat Bread",
    price: "3.90",
    rating: "4.6",
    featured: false,
    stock: 27,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=1200&auto=format&fit=crop",
    description: "Fresh-baked whole wheat loaf with soft crumb and nutty flavor for toast, sandwiches, and breakfast service.",
  }),
  createSeedProduct({
    name: "Plain Bagel Six Pack",
    price: "4.20",
    rating: "4.4",
    featured: false,
    stock: 22,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1608198093002-ad4e005484ec?q=80&w=1200&auto=format&fit=crop",
    description: "6 plain bagels baked for breakfast sandwiches, cream cheese spreads, and office snack setups.",
  }),
  createSeedProduct({
    name: "Roasted Tomato Pasta Sauce",
    price: "4.30",
    rating: "4.6",
    featured: false,
    stock: 40,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?q=80&w=1200&auto=format&fit=crop",
    description: "680 g roasted tomato sauce with garlic and herbs for pasta, pizza, lasagna, and weeknight dinners.",
  }),
  createSeedProduct({
    name: "Red Lentils 1 kg",
    price: "4.90",
    rating: "4.7",
    featured: false,
    stock: 43,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1515543904379-3d757afe72e1?q=80&w=1200&auto=format&fit=crop",
    description: "Fast-cooking red lentils for soups, curries, stews, and budget-friendly protein-packed meals.",
  }),
  createSeedProduct({
    name: "Canned Chickpeas Four Pack",
    price: "5.60",
    rating: "4.5",
    featured: false,
    stock: 36,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=1200&auto=format&fit=crop",
    description: "4 cans of cooked chickpeas for salads, hummus, soups, grain bowls, and easy pantry meals.",
  }),
  createSeedProduct({
    name: "Fresh Basil Bunch",
    price: "2.60",
    rating: "4.5",
    featured: false,
    stock: 21,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1618375569909-3c8616cf7733?q=80&w=1200&auto=format&fit=crop",
    description: "One fragrant basil bunch for pasta, pizza, salads, pestos, and fresh garnish service.",
  }),
  createSeedProduct({
    name: "Button Mushroom Tray",
    price: "4.40",
    rating: "4.6",
    featured: false,
    stock: 24,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1504545102780-26774c1bb073?q=80&w=1200&auto=format&fit=crop",
    description: "300 g button mushrooms ready for sauteing, pasta, omelets, pizzas, and savory side dishes.",
  }),
  createSeedProduct({
    name: "Onion and Garlic Combo",
    price: "4.10",
    rating: "4.7",
    featured: false,
    stock: 49,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1508747703725-719777637510?q=80&w=1200&auto=format&fit=crop",
    description: "Kitchen starter combo with 1 kg yellow onions plus two garlic bulbs for daily cooking foundations.",
  }),
  createSeedProduct({
    name: "Family Veggie Soup Box",
    price: "14.80",
    rating: "4.8",
    featured: true,
    stock: 18,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1466637574441-749b8f19452f?q=80&w=1200&auto=format&fit=crop",
    description: "Curated soup box with carrots, celery, onions, potatoes, tomatoes, and herbs for batch cooking at home.",
  }),
  createSeedProduct({
    name: "Blackberry Dessert Cup",
    price: "6.40",
    rating: "4.7",
    featured: false,
    stock: 18,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1515037893149-de7f840978e2?q=80&w=1200&auto=format&fit=crop",
    description: "Fresh blackberries packed for dessert topping, breakfast bowls, bakery prep, and premium fruit cups.",
  }),
  createSeedProduct({
    name: "Clementine Easy Peel Bag",
    price: "7.50",
    rating: "4.6",
    featured: false,
    stock: 39,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1584306670957-acf935f5033c?q=80&w=1200&auto=format&fit=crop",
    description: "2 kg clementine bag with sweet easy-peel citrus for lunch boxes, snacking, and winter fruit platters.",
  }),
  createSeedProduct({
    name: "Red Globe Grape Cluster",
    price: "8.30",
    rating: "4.6",
    featured: false,
    stock: 26,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1537640538966-79f369143f8f?q=80&w=1200&auto=format&fit=crop",
    description: "Large red grapes with a firm bite and sweet finish, prepared for table fruit and entertaining boards.",
  }),
  createSeedProduct({
    name: "Passion Fruit Six Pack",
    price: "7.90",
    rating: "4.5",
    featured: false,
    stock: 15,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1615485925873-9d3f2ea10d04?q=80&w=1200&auto=format&fit=crop",
    description: "6 passion fruits with aromatic pulp for mocktails, yogurt, plated desserts, and tropical sauces.",
  }),
  createSeedProduct({
    name: "Apricot Orchard Tray",
    price: "6.60",
    rating: "4.5",
    featured: false,
    stock: 20,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1596591868231-05e7f528fac1?q=80&w=1200&auto=format&fit=crop",
    description: "Soft apricots with delicate sweetness for snacking, pastry filling, fruit salads, and preserves.",
  }),
  createSeedProduct({
    name: "Nectarine Summer Box",
    price: "7.20",
    rating: "4.6",
    featured: true,
    stock: 22,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1596591868231-05e7f528fac1?q=80&w=1200&auto=format&fit=crop",
    description: "6 nectarines with smooth skin and juicy flesh, packed for summer desserts, snacks, and brunch service.",
  }),
  createSeedProduct({
    name: "Guava Tropical Pack",
    price: "8.10",
    rating: "4.4",
    featured: false,
    stock: 13,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?q=80&w=1200&auto=format&fit=crop",
    description: "4 ripe guavas with fragrant pink flesh for juices, jams, breakfast fruit, and smoothie blends.",
  }),
  createSeedProduct({
    name: "Coconut Water Pair",
    price: "6.90",
    rating: "4.5",
    featured: false,
    stock: 18,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1587132137056-bfbf0166836e?q=80&w=1200&auto=format&fit=crop",
    description: "Two young coconuts for chilled hydration, tropical dessert plating, and fresh juice service.",
  }),
  createSeedProduct({
    name: "Green Apple Snack Pack",
    price: "8.20",
    rating: "4.7",
    featured: false,
    stock: 34,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?q=80&w=1200&auto=format&fit=crop",
    description: "Tart green apples with clean crunch for salads, dipping, baking, and desk-side snacking.",
  }),
  createSeedProduct({
    name: "Pink Lady Apple Tote",
    price: "10.20",
    rating: "4.8",
    featured: true,
    stock: 29,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?q=80&w=1200&auto=format&fit=crop",
    description: "Premium Pink Lady apples with a crisp sweet finish for lunch prep, cheese boards, and family fruit bowls.",
  }),
  createSeedProduct({
    name: "Fresh Fig Punnet",
    price: "8.70",
    rating: "4.5",
    featured: false,
    stock: 12,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1519996529931-28324d5a630e?q=80&w=1200&auto=format&fit=crop",
    description: "Tender fresh figs for cheese pairing, pastry garnish, breakfast service, and premium seasonal snacking.",
  }),
  createSeedProduct({
    name: "Star Fruit Tropical Tray",
    price: "7.40",
    rating: "4.3",
    featured: false,
    stock: 9,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1619566636858-adf3ef46400b?q=80&w=1200&auto=format&fit=crop",
    description: "Star fruit with bright tart-sweet flavor, mainly suited for fruit platters, juices, and decorative slicing.",
  }),
  createSeedProduct({
    name: "Mandarin Citrus Box",
    price: "8.80",
    rating: "4.7",
    featured: true,
    stock: 37,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1584306670957-acf935f5033c?q=80&w=1200&auto=format&fit=crop",
    description: "Easy-peel mandarins for family snacking, school lunches, office fruit bowls, and fresh desserts.",
  }),
  createSeedProduct({
    name: "Fresh Date Palm Box",
    price: "9.30",
    rating: "4.6",
    featured: false,
    stock: 16,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1603048297172-c92544798d5a?q=80&w=1200&auto=format&fit=crop",
    description: "Soft fresh dates with caramel notes, ideal for gifting, Ramadan tables, smoothies, and snack platters.",
  }),
  createSeedProduct({
    name: "Mini Fruit Lunch Box",
    price: "12.60",
    rating: "4.7",
    featured: true,
    stock: 21,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?q=80&w=1200&auto=format&fit=crop",
    description: "Curated small fruit box with apples, bananas, clementines, and grapes for weekly snack planning.",
  }),
  createSeedProduct({
    name: "Juicing Citrus Crate",
    price: "18.20",
    rating: "4.8",
    featured: true,
    stock: 14,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1547514701-42782101795e?q=80&w=1200&auto=format&fit=crop",
    description: "Bulk oranges, lemons, and grapefruit selected for high-yield juicing at home or for small cafes.",
  }),
  createSeedProduct({
    name: "Berry Mix Duo Pack",
    price: "11.50",
    rating: "4.8",
    featured: true,
    stock: 17,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1498557850523-fd3d118b962e?q=80&w=1200&auto=format&fit=crop",
    description: "Two-pack berry mix featuring blueberries and raspberries for brunch, desserts, and healthy breakfast prep.",
  }),
  createSeedProduct({
    name: "Salad Cucumber Twin Pack",
    price: "3.20",
    rating: "4.5",
    featured: false,
    stock: 39,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?q=80&w=1200&auto=format&fit=crop",
    description: "2 crisp cucumbers for salads, sandwiches, infused water, and cold lunch prep throughout the week.",
  }),
  createSeedProduct({
    name: "Romaine Lettuce Hearts",
    price: "3.70",
    rating: "4.6",
    featured: false,
    stock: 24,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1622205313162-be1d5712a43c?q=80&w=1200&auto=format&fit=crop",
    description: "Two romaine hearts for Caesar salads, wraps, burger topping, and fresh crunchy side dishes.",
  }),
  createSeedProduct({
    name: "Cauliflower Head",
    price: "4.10",
    rating: "4.5",
    featured: false,
    stock: 20,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1510626176961-4b37d41d4b48?q=80&w=1200&auto=format&fit=crop",
    description: "One fresh cauliflower head for roasting, mash, rice alternatives, soups, and vegetarian mains.",
  }),
  createSeedProduct({
    name: "Zucchini Grill Pack",
    price: "4.40",
    rating: "4.5",
    featured: false,
    stock: 22,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1466637574441-749b8f19452f?q=80&w=1200&auto=format&fit=crop",
    description: "Four zucchini ready for grilling, roasting, noodles, casseroles, and quick sauteed dinners.",
  }),
  createSeedProduct({
    name: "Red Onion Mesh Bag",
    price: "3.60",
    rating: "4.6",
    featured: false,
    stock: 46,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1508747703725-719777637510?q=80&w=1200&auto=format&fit=crop",
    description: "1 kg red onions for salads, roasting, curries, burgers, and all-purpose kitchen prep.",
  }),
  createSeedProduct({
    name: "Garlic Farm Bulb Pack",
    price: "2.90",
    rating: "4.7",
    featured: false,
    stock: 54,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1508747703725-719777637510?q=80&w=1200&auto=format&fit=crop",
    description: "Three fresh garlic bulbs for sauces, marinades, sauteing, soups, and daily savory cooking.",
  }),
  createSeedProduct({
    name: "Avocado Oil Bottle",
    price: "10.80",
    rating: "4.7",
    featured: false,
    stock: 19,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?q=80&w=1200&auto=format&fit=crop",
    description: "500 ml avocado oil with a clean finish and high-heat versatility for roasting and searing.",
  }),
  createSeedProduct({
    name: "Basmati Rice 2 kg",
    price: "8.10",
    rating: "4.8",
    featured: true,
    stock: 37,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?q=80&w=1200&auto=format&fit=crop",
    description: "Long-grain basmati rice with fragrant aroma for biryani, curries, bowls, and dinner service.",
  }),
  createSeedProduct({
    name: "Quinoa Grain Bag",
    price: "6.70",
    rating: "4.6",
    featured: false,
    stock: 25,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?q=80&w=1200&auto=format&fit=crop",
    description: "1 kg quinoa for salads, grain bowls, healthy sides, and protein-rich meal prep.",
  }),
  createSeedProduct({
    name: "Tuna Fillet Portions",
    price: "15.40",
    rating: "4.7",
    featured: false,
    stock: 12,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1544943910-4c1dc44aab44?q=80&w=1200&auto=format&fit=crop",
    description: "Fresh tuna portions suitable for grilling, searing, salads, and premium seafood dinners.",
  }),
  createSeedProduct({
    name: "Ground Turkey Tray",
    price: "9.90",
    rating: "4.5",
    featured: false,
    stock: 17,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?q=80&w=1200&auto=format&fit=crop",
    description: "Lean ground turkey for burgers, meatballs, tacos, pasta sauces, and lighter weeknight meals.",
  }),
  createSeedProduct({
    name: "Halloumi Grill Cheese",
    price: "6.20",
    rating: "4.6",
    featured: false,
    stock: 20,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1552767059-ce182ead6c1b?q=80&w=1200&auto=format&fit=crop",
    description: "Firm grillable cheese for salads, wraps, skewers, and Mediterranean-inspired home meals.",
  }),
  createSeedProduct({
    name: "Mozzarella Pizza Ball",
    price: "4.90",
    rating: "4.6",
    featured: false,
    stock: 28,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1552767059-ce182ead6c1b?q=80&w=1200&auto=format&fit=crop",
    description: "Soft mozzarella for pizza, caprese salads, baked pasta, and family dinner prep.",
  }),
  createSeedProduct({
    name: "Cottage Cheese Tub",
    price: "4.30",
    rating: "4.4",
    featured: false,
    stock: 24,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1571212515416-fca88b972a7f?q=80&w=1200&auto=format&fit=crop",
    description: "500 g cottage cheese for breakfast, toast topping, healthy bowls, and high-protein snacks.",
  }),
  createSeedProduct({
    name: "Vanilla Yogurt Cup Set",
    price: "4.60",
    rating: "4.5",
    featured: false,
    stock: 30,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1571212515416-fca88b972a7f?q=80&w=1200&auto=format&fit=crop",
    description: "Four vanilla yogurt cups for packed lunches, breakfast, and chilled dessert moments.",
  }),
  createSeedProduct({
    name: "Croissant Breakfast Box",
    price: "6.10",
    rating: "4.7",
    featured: true,
    stock: 18,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1555507036-ab794f4afe5a?q=80&w=1200&auto=format&fit=crop",
    description: "6 butter croissants baked for breakfast service, coffee pairing, office catering, and weekend brunch.",
  }),
  createSeedProduct({
    name: "Sourdough Sandwich Loaf",
    price: "4.80",
    rating: "4.7",
    featured: false,
    stock: 21,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=1200&auto=format&fit=crop",
    description: "Artisan sourdough loaf with crisp crust and chewy crumb for toast, grilled sandwiches, and soup service.",
  }),
  createSeedProduct({
    name: "Wrap Tortilla Pack",
    price: "3.90",
    rating: "4.5",
    featured: false,
    stock: 33,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?q=80&w=1200&auto=format&fit=crop",
    description: "8 soft tortillas for wraps, quesadillas, lunch prep, and quick family dinners.",
  }),
  createSeedProduct({
    name: "Tomato Ketchup Family Squeeze",
    price: "3.70",
    rating: "4.4",
    featured: false,
    stock: 35,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?q=80&w=1200&auto=format&fit=crop",
    description: "Large ketchup bottle for fries, burgers, sandwiches, and everyday family meals.",
  }),
  createSeedProduct({
    name: "Mayonnaise Kitchen Jar",
    price: "4.20",
    rating: "4.5",
    featured: false,
    stock: 29,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?q=80&w=1200&auto=format&fit=crop",
    description: "Classic mayonnaise for sandwiches, salads, marinades, dips, and home kitchen staples.",
  }),
  createSeedProduct({
    name: "Black Bean Pantry Bag",
    price: "4.80",
    rating: "4.6",
    featured: false,
    stock: 31,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1515543904379-3d757afe72e1?q=80&w=1200&auto=format&fit=crop",
    description: "1 kg dried black beans for soups, burrito bowls, stews, and affordable protein-rich meals.",
  }),
  createSeedProduct({
    name: "Green Pea Freezer Bag",
    price: "3.60",
    rating: "4.5",
    featured: false,
    stock: 27,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=1200&auto=format&fit=crop",
    description: "Frozen peas for rice dishes, soups, pot pies, side dishes, and everyday quick cooking.",
  }),
  createSeedProduct({
    name: "Fresh Ginger Root Pack",
    price: "3.10",
    rating: "4.6",
    featured: false,
    stock: 34,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?q=80&w=1200&auto=format&fit=crop",
    description: "Fresh ginger roots for tea, stir-fries, marinades, soups, and wellness-focused kitchen prep.",
  }),
  createSeedProduct({
    name: "Parsley Herb Bundle",
    price: "2.40",
    rating: "4.4",
    featured: false,
    stock: 26,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1618375569909-3c8616cf7733?q=80&w=1200&auto=format&fit=crop",
    description: "Fresh parsley bundle for garnish, chimichurri, soups, salads, and bright finishing notes.",
  }),
  createSeedProduct({
    name: "Meal Prep Protein Box",
    price: "29.90",
    rating: "4.8",
    featured: true,
    stock: 10,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=1200&auto=format&fit=crop",
    description: "Mixed weekly protein box with chicken, eggs, yogurt, and pantry staples for structured meal prep.",
  }),
  createSeedProduct({
    name: "Snack Carrot and Celery Pack",
    price: "4.20",
    rating: "4.5",
    featured: false,
    stock: 23,
    category: "foods",
    imageUrl: "https://images.unsplash.com/photo-1447175008436-170170753d52?q=80&w=1200&auto=format&fit=crop",
    description: "Ready-to-prep carrot and celery pack for dips, lunchboxes, soup bases, and healthy snack trays.",
  }),
  createSeedProduct({
    name: "Premium Breakfast Fruit Basket",
    price: "19.40",
    rating: "4.9",
    featured: true,
    stock: 12,
    category: "fruits",
    imageUrl: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?q=80&w=1200&auto=format&fit=crop",
    description: "Curated breakfast fruit basket with berries, citrus, apples, and bananas for households, gifting, and brunch service.",
  }),
]);
